apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ims-ingress
  namespace: inventory-management
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /api/ims/v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ims-service
                port:
                  number: 8080